Repository team-pofo/frontend, pull requests merged in 2025-01, with the labels that each got.

#39 Feature/#38/user logo
  public/icons/heart.svg
  public/icons/power.svg
  public/icons/user_2.svg
  src/components/Navigation/Navigation.tsx
Labels: enhancement, style

#45 feat (#43): 배포 workflow 제작
  .github/workflows/CD-web-develop.yml
Labels: enhancement

#58 Feature/#57/user artcle
  src/components/Mypage/MyProjects/MyProjects.tsx
  src/components/Mypage/MypageLayout.tsx
  src/components/Navigation/Navigation.tsx
  src/components/ProjectCard/Mypage/MypageProjectCard.tsx
  src/components/ProjectCard/ProjectCard.tsx
  src/components/ProjectCard/styles.ts
  src/lib/interface/iProjectCard.ts
  src/pages/[username]/editprofile.tsx
  src/pages/[username]/index.tsx
  src/pages/[username]/likeprojects.tsx
  src/pages/[username]/projects.tsx
  src/services/gql/searchProject.ts
Labels: enhancement

#60 style. #59-프로젝트 카드 호버시 이벤트 추가
  src/components/ProjectCard/styles.ts
Labels: enhancement, style

#64 refactor. #63-마이페이지 재렌더링 방지 위해 중첩 레이아웃 적용
  src/components/Layout/MypageLayout.tsx
  src/components/Layout/styles.ts
  src/components/Mypage/styles.ts
  src/pages/[username]/editprofile.tsx
  src/pages/[username]/likeprojects.tsx
  src/pages/[username]/projects.tsx
  src/pages/_app.tsx
  src/pages/index.tsx
Labels: enhancement, refactor

#65 Feature/#62/profile image
  src/components/Layout/MypageLayout.tsx
Labels: enhancement

#70 Feature/#66/newpostformlimit
  src/components/Navigation/Navigation.tsx
  src/components/Newpost/Newpost.tsx
  src/components/ProjectCard/styles.ts
  src/pages/_app.tsx
  src/pages/newpost/index.tsx
  src/pages/project/[id]/index.tsx
Labels: enhancement, style

#71 Style/#69/new post UI
  package-lock.json
  package.json
  src/components/Home/HomeSearch.tsx
  src/components/Home/styles.ts
  src/components/Newpost/Newpost.tsx
  src/components/SelectStackType/SelectStack.tsx
  src/components/SelectStackType/SelectStackType.tsx
  src/components/SelectStackType/SelectType.tsx
  src/components/SelectStackType/SelectedStackType.tsx
  src/components/SelectStackType/styles.ts
  src/components/ui/badge.tsx
  src/components/ui/command.tsx
  src/components/ui/dialog.tsx
Labels: enhancement, style, refactor
